def t(lang: str, code: str) -> str:
    source = TEXTS.get(lang, TEXTS["en"])
    return source[code] if code in source else TEXTS["en"][code]


TEXTS = {
    "ru": {
        "start_title": "My TON Provider",
        "start_body": "<b>Отслеживайте статус провайдеров</b> — телеметрия, уведомления и многое другое.",
        "open_app": "Открыть приложение",
        "reward_title": "Получена награда",
        "alert_provider": "Провайдер:",
        "alert_restarted": "Сервис {service} перезапущен",
        "bag_added_title": "Добавлен бэг",
        "bags_added_title": "Добавлены бэги: {n}",
        "list_more": "… и ещё {n}",
        "monthly_title": "Ежемесячный отчёт",
        "monthly_earned": "Заработано",
        "monthly_space": "Прирост места",
        "monthly_traffic_in": "Трафик входящий",
        "monthly_traffic_out": "Трафик исходящий",
        "alert_detected_not_online": "Провайдер офлайн",
        "alert_detected_telemetry_lost": "Телеметрия не поступает",
        "alert_detected_cpu_high": "Повышенная нагрузка CPU",
        "alert_detected_ram_high": "Повышенная загрузка RAM",
        "alert_detected_network_high": "Повышенная нагрузка сети",
        "alert_detected_disk_load_high": "Повышенная нагрузка на диск",
        "alert_detected_disk_space_low": "Заканчивается место на диске",
        "alert_resolved_not_online": "Провайдер снова онлайн",
        "alert_resolved_telemetry_lost": "Телеметрия снова поступает",
        "alert_resolved_cpu_high": "Нагрузка CPU нормализовалась",
        "alert_resolved_ram_high": "Загрузка RAM нормализовалась",
        "alert_resolved_network_high": "Нагрузка сети нормализовалась",
        "alert_resolved_disk_load_high": "Нагрузка на диск нормализовалась",
        "alert_resolved_disk_space_low": "Место на диске восстановлено",
    },
    "en": {
        "start_title": "My TON Provider",
        "start_body": "<b>Track your providers' status</b> —\ntelemetry, notifications and much more.",
        "open_app": "Open the app",
        "reward_title": "Reward received",
        "alert_provider": "Provider:",
        "alert_restarted": "Service {service} restarted",
        "bag_added_title": "Bag added",
        "bags_added_title": "Bags added: {n}",
        "list_more": "… and {n} more",
        "monthly_title": "Monthly report",
        "monthly_earned": "Earned",
        "monthly_space": "Space added",
        "monthly_traffic_in": "Traffic in",
        "monthly_traffic_out": "Traffic out",
        "alert_detected_not_online": "Provider is not online",
        "alert_detected_telemetry_lost": "Telemetry stopped coming in",
        "alert_detected_cpu_high": "Elevated CPU load",
        "alert_detected_ram_high": "Elevated RAM usage",
        "alert_detected_network_high": "Elevated network load",
        "alert_detected_disk_load_high": "Elevated disk load",
        "alert_detected_disk_space_low": "Disk space running low",
        "alert_resolved_not_online": "Provider is back online",
        "alert_resolved_telemetry_lost": "Telemetry is coming in again",
        "alert_resolved_cpu_high": "CPU load is back to normal",
        "alert_resolved_ram_high": "RAM usage is back to normal",
        "alert_resolved_network_high": "Network load is back to normal",
        "alert_resolved_disk_load_high": "Disk load is back to normal",
        "alert_resolved_disk_space_low": "Disk space recovered",
    },
}
