"""initial schema

Revision ID: d5a2f8b1c470
Revises:
Create Date: 2026-07-14 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.models._base import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = 'd5a2f8b1c470'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('pubkey', sa.String(length=64), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('cpu_load_percent', sa.Float(), nullable=True),
    sa.Column('ram_load_percent', sa.Float(), nullable=True),
    sa.Column('disk_load_percent', sa.Float(), nullable=True),
    sa.Column('net_mbps', sa.Float(), nullable=True),
    sa.Column('net_capacity_mbps', sa.Float(), nullable=True),
    sa.Column('disk_used', sa.BigInteger(), nullable=True),
    sa.Column('disk_total', sa.BigInteger(), nullable=True),
    sa.Column('last_wallet_lt', sa.BigInteger(), nullable=True),
    sa.Column('last_bytes_recv', sa.BigInteger(), nullable=True),
    sa.Column('last_bytes_sent', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('earned', sa.BigInteger(), nullable=False),
    sa.Column('traffic_in', sa.BigInteger(), nullable=False),
    sa.Column('traffic_out', sa.BigInteger(), nullable=False),
    sa.Column('telemetry_pass', sa.String(length=255), nullable=True),
    sa.Column('telemetry_at', UTCDateTime(), nullable=True),
    sa.Column('ton_storage_uptime', sa.Float(), nullable=True),
    sa.Column('ton_storage_githash', sa.String(length=40), nullable=True),
    sa.Column('ton_storage_provider_uptime', sa.Float(), nullable=True),
    sa.Column('ton_storage_provider_githash', sa.String(length=40), nullable=True),
    sa.Column('balance_at', UTCDateTime(), nullable=True),
    sa.Column('last_online_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pubkey', name=op.f('pk_providers'))
    )
    op.create_table('providers_history',
    sa.Column('pubkey', sa.String(length=64), nullable=False),
    sa.Column('archived_at', UTCDateTime(), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('cpu_load_percent', sa.Float(), nullable=True),
    sa.Column('ram_load_percent', sa.Float(), nullable=True),
    sa.Column('disk_load_percent', sa.Float(), nullable=True),
    sa.Column('net_mbps', sa.Float(), nullable=True),
    sa.Column('net_capacity_mbps', sa.Float(), nullable=True),
    sa.Column('disk_used', sa.BigInteger(), nullable=True),
    sa.Column('disk_total', sa.BigInteger(), nullable=True),
    sa.Column('last_wallet_lt', sa.BigInteger(), nullable=True),
    sa.Column('last_bytes_recv', sa.BigInteger(), nullable=True),
    sa.Column('last_bytes_sent', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('earned', sa.BigInteger(), nullable=False),
    sa.Column('traffic_in', sa.BigInteger(), nullable=False),
    sa.Column('traffic_out', sa.BigInteger(), nullable=False),
    sa.Column('telemetry_pass', sa.String(length=255), nullable=True),
    sa.Column('telemetry_at', UTCDateTime(), nullable=True),
    sa.Column('ton_storage_uptime', sa.Float(), nullable=True),
    sa.Column('ton_storage_githash', sa.String(length=40), nullable=True),
    sa.Column('ton_storage_provider_uptime', sa.Float(), nullable=True),
    sa.Column('ton_storage_provider_githash', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('pubkey', 'archived_at', name=op.f('pk_providers_history'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=8), nullable=False),
    sa.Column('explorer', sa.String(length=16), nullable=False),
    sa.Column('favorites', sa.JSON(), nullable=False),
    sa.Column('alert_types', sa.JSON(), nullable=False),
    sa.Column('alert_thresholds', sa.JSON(), nullable=False),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('contracts',
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('bag_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Integer(), nullable=True),
    sa.Column('reason_at', UTCDateTime(), nullable=True),
    sa.Column('owner_address', sa.String(length=64), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['provider_pubkey'], ['providers.pubkey'], name=op.f('fk_contracts_provider_pubkey_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_pubkey', 'address', name=op.f('pk_contracts'))
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('telemetry_pass', sa.String(length=255), nullable=True),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['provider_pubkey'], ['providers.pubkey'], name=op.f('fk_subscriptions_provider_pubkey_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'provider_pubkey', name=op.f('pk_subscriptions'))
    )
    op.create_table('alerts',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('notified_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'provider_pubkey'], ['subscriptions.user_id', 'subscriptions.provider_pubkey'], name=op.f('fk_alerts_user_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'provider_pubkey', 'alert_type', name=op.f('pk_alerts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('subscriptions')
    op.drop_table('contracts')
    op.drop_table('users')
    op.drop_table('providers_history')
    op.drop_table('providers')
    # ### end Alembic commands ###
